INSERT INTO USER_(ID, USERNAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED)
VALUES (1, 'admin', /*admin*/'$2a$08$HzYx6pZtO74VycjhWQ5fW.G43QOGTy/YtuGBAARQduidiIvbzhC2i', FALSE, FALSE, FALSE, TRUE);
INSERT INTO USER_(ID, USERNAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED)
VALUES (2, 'guest', /*guest*/'$2a$08$qleLhpaqHJJIBtZ45TsoCePiGgAb0H1543LwAiXi3yTFWumPAJ8ei', FALSE, FALSE, FALSE, TRUE);

INSERT INTO AUTHORITY(ID, AUTHORITY) VALUES (1, 'READ');
INSERT INTO AUTHORITY(ID, AUTHORITY) VALUES (2, 'WRITE');

INSERT INTO AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (1, 2);
INSERT INTO AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (2, 1);

CREATE TABLE OAUTH_CLIENT_DETAILS (
  CLIENT_ID VARCHAR(255) PRIMARY KEY,
  RESOURCE_IDS VARCHAR(255),
  CLIENT_SECRET VARCHAR(255),
  SCOPE VARCHAR(255),
  AUTHORIZED_GRANT_TYPES VARCHAR(255),
  WEB_SERVER_REDIRECT_URI VARCHAR(255),
  AUTHORITIES VARCHAR(255),
  ACCESS_TOKEN_VALIDITY INTEGER,
  REFRESH_TOKEN_VALIDITY INTEGER,
  ADDITIONAL_INFORMATION VARCHAR(4096),
  AUTOAPPROVE VARCHAR(255)
);

CREATE TABLE OAUTH_CLIENT_TOKEN (
  TOKEN_ID VARCHAR(255),
  TOKEN VARBINARY,
  AUTHENTICATION_ID VARCHAR(255) PRIMARY KEY,
  USER_NAME VARCHAR(255),
  CLIENT_ID VARCHAR(255)
);

CREATE TABLE OAUTH_ACCESS_TOKEN (
  TOKEN_ID VARCHAR(255),
  TOKEN VARBINARY,
  AUTHENTICATION_ID VARCHAR(255) PRIMARY KEY,
  USER_NAME VARCHAR(255),
  CLIENT_ID VARCHAR(255),
  AUTHENTICATION VARBINARY,
  REFRESH_TOKEN VARCHAR(255)
);

CREATE TABLE OAUTH_REFRESH_TOKEN (
  TOKEN_ID VARCHAR(255),
  TOKEN VARBINARY,
  AUTHENTICATION VARBINARY
);

CREATE TABLE OAUTH_CODE (
  CODE VARCHAR(255),
  AUTHENTICATION VARBINARY
);

CREATE TABLE OAUTH_APPROVALS (
  USERID VARCHAR(255),
  CLIENTID VARCHAR(255),
  SCOPE VARCHAR(255),
  STATUS VARCHAR(10),
  EXPIRESAT TIMESTAMP,
  LASTMODIFIEDAT TIMESTAMP
);

INSERT INTO OAUTH_CLIENT_DETAILS(CLIENT_ID, RESOURCE_IDS, CLIENT_SECRET, SCOPE, AUTHORIZED_GRANT_TYPES, AUTHORITIES, ACCESS_TOKEN_VALIDITY, REFRESH_TOKEN_VALIDITY)
	VALUES ('read-client', 'resource-server',/*read123*/'$2a$04$WvTSXWt4DZ.dV3Fsig8he.ExWx0D704NIrNSuvEgJjNgmwKzpJBVK','read', 'password,authorization_code,refresh_token,implicit', 'USER', 10800, 2592000);

INSERT INTO OAUTH_CLIENT_DETAILS(CLIENT_ID, RESOURCE_IDS, CLIENT_SECRET, SCOPE, AUTHORIZED_GRANT_TYPES, AUTHORITIES, ACCESS_TOKEN_VALIDITY, REFRESH_TOKEN_VALIDITY)
	VALUES ('read-write-client', 'resource-server',/*write123*/'$2a$04$Y.xhvPAYyLka3kp667rwb.Xf7BekesgUH7YMrbVL6DEQ9vbdmO6iW', 'read,write', 'password,authorization_code,refresh_token,implicit', 'USER', 10800, 2592000);